name: Generate ASCII Artwork
on:
  workflow_dispatch:
jobs:
  build-artwork:
    runs-on:
      - ubuntu-latest
    steps:
    - run: |-
        # Build a message by invoking ADVICESLIP API
        curl -s https://api.adviceslip.com/advice > advice.json
        cat advice.json
        
        # Test to make sure the advice message has more than 5 words.
        cat advice.json | jq -r .slip.advice > advice.message
        [ $(wc -w < advice.message) -gt 5 ] && [ $(wc -w < advice.message) -le 500 ] && echo "$(cat advice.message)" || (echo "Advice - $(cat advice.message) has invalid word count" && exit 1)
        
        # Deploy
        sudo apt-get install cowsay -y
        echo $PATH
        export PATH="$PATH:/usr/games:/usr/local/games"
        cat advice.message | cowsay -f $(ls /usr/share/cowsay/cows | shuf -n 1)
